# Generated by Django 4.0.4 on 2022-05-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Division_Name', models.CharField(blank=True, max_length=120, null=True)),
                ('District_Name', models.CharField(blank=True, max_length=120, null=True)),
                ('Crop_Year', models.IntegerField(blank=True, null=True)),
                ('Season', models.CharField(blank=True, max_length=120, null=True)),
                ('Crop', models.CharField(blank=True, max_length=120, null=True)),
                ('Area', models.CharField(blank=True, max_length=120, null=True)),
                ('Production', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
