# Generated by Django 4.0.4 on 2022-05-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.IntegerField(blank=True, null=True)),
                ('P', models.IntegerField(blank=True, null=True)),
                ('K', models.IntegerField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, max_length=120, null=True)),
                ('humidity', models.FloatField(blank=True, max_length=120, null=True)),
                ('ph', models.FloatField(blank=True, max_length=120, null=True)),
                ('rainfall', models.FloatField(blank=True, max_length=120, null=True)),
                ('label', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='production',
            name='Area',
            field=models.IntegerField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='Production',
            field=models.IntegerField(blank=True, max_length=120, null=True),
        ),
    ]
